name: Deploy to FTP server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Build the application
      run: npm run build

    - name: Deploy to FTP server
      uses: SamKirkland/FTP-Deploy-Action@v1
      with:
        ftp-server: ftp.example.com
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./build
        remote-dir: /public_html
